### ISSUE TITLE
Discussion on use of the "Prerelease" scope

### ISSUE THREAD

**Issue by AlphaKretin** [ProjectIgnis/BabelCDB#10]
Some confusion has arisen in discussions about the "Prerelease" scope, so this is a discussion issue for staff to collectively decide on how it should be used. Once the decision has been made, we need to document it in the guidelines.

**Comment by AlphaKretin** [comment]
In my opinion, the Prerelease scope should be removed from a card at the same time it receives its official ID. The point of it is to distinguish cards that are not yet released, and as such do not reflect any official format and may not have rulings. As soon as they are released, they should be legal for play in OCG (or occasionally TCG, when appropriate) rooms.

**Comment by EerieCode** [comment]
Personally, I think there should be a grace period before changing the OT. If the purpose is to distinguish cards in an unofficial format, then logically they should be released once they _follow_ the format, that is, once the rulings are available, have been translated, and we're sure the scripts follow them.

**Comment by NaimSantos** [comment]
I agree with Alpha that they should have the prerelease OT removed as soon as the product they are in is made available in their region. At that point, such cards are no longer prereleases: they are already available for players in those regions.

**Comment by AlphaKretin** [comment]
I do understand the point about rulings, but we should formalise a process for listing issues and testing them as soon as we can so that, depending on which way we go, either we can get them out of prerelease as soon as possible, or they're untested while released for as little time as possible.

**Comment by AlphaKretin** [comment]
While we still absolutely need the workflow I mentioned before to do it ourselves, in this specific case we may well have had it done for us so we can expedite remove the Prerelease tag from ROTD. https://github.com/ProjectIgnis/CardScripts/pull/208

**Comment by kevinlul** [comment]
Discussion has been resolved: the prerelease scope is removed when cards first become official product in the corresponding region.
