### ISSUE TITLE
Hypersped Rush Road official database

### ISSUE THREAD

**Issue by marikisthar** [ProjectIgnis/BabelCDB#4]
Cards from Hyperspeed Rush Road (cards-rush-prerelease.cdb) already released in OCG, could you make them to official cdb ones?

https://yugipedia.com/wiki/Deck_Modification_Pack_-_Hyperspeed_Rush_Road!!

and a lil question, if the cdb already official, did the setcode change or still same as pre-release one?? 

tnx in advance

**Comment by EerieCode** [comment]
Unauthorized users are not allowed to make pull requests or issues on this repo. This issue will now be closed: DO NOT open other issues or pulls on this repo again. Consider this a final warning: next infraction will be met with an immediate and permanent ban from the repo.
